### PR TITLE
IB-536

### PR DESCRIPTION
**Pull request by VitalyT-Inspera**
Update CKEditor to 40.2

There are too many files to have any meaningful review
I am updating it to 40.2 version because in this version defect with sticky header in ckEditor was fixed
It will resolve IB-536 tiket
I have built and verify sample that presented in packages\ckeditor5-build-classic\sample\index.html
We have to use yarn instead of npm cause `npm install` fail (on my machine (windows)) I am afraid that we will have to update build agent after this update will be merged (some of packages require node >=18 agent has 16) and keep an eye on npm install step

PS: I do not know why we need complete fork of CKEditor, it would be much easier to have just 'superbuild 'project instead of giant CKEditor project?

### CODE REVIEW

**Comment by gmcatalin** [comment]
Does this include both fork update and you changes ? They should be separate if so.

**Comment by VitalyT-Inspera** [comment]
> Does this include both fork update and you changes ? They should be separate if so.

It is only fork update and changes that fixes initial build after this. 
I did not include ticket with bringing new features here.
What was done here:
merged ckEditor5 version 40.2
ckeditor.js was replaced by ckeditor.ts (by merge)
import path fixes to make build work

**Review by jarlep — APPROVED** [review]
It is not possible to see the diff here, but if its only an upgrade of CKEditor its ok, given that it is well tested and also reported to the CP team so it can be tested there too. Mention Alex on the task

**Comment by gmcatalin** [comment]
```It is only fork update and changes that fixes initial build after this.```
What fixes ?
I guess we'll see if it works with the TC deploy.

**Pull request merged**
